version: '3'
services:
  jupyter:
    build:
      context: docker/jupyter
    env_file:
      - docker/jupyter/jupyter.env
    ports:
      - "8888:8888"
    working_dir: /home/jovyan/work
    volumes:
      - ./source:/home/jovyan/work/source
      - ./data:/home/jovyan/work/data
